# Generated by Django 5.2.6 on 2025-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.PositiveBigIntegerField(editable=False),
        ),
    ]
