# Generated by Django 5.2.6 on 2025-09-30 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300)),
                ('cityname', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='ExistTrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traintype', models.CharField(max_length=100)),
                ('depratordate', models.DateField()),
                ('depratortime', models.TimeField(default=django.utils.timezone.now)),
                ('price', models.BigIntegerField(default=2000000)),
                ('returndate', models.DateField(blank=True)),
                ('returntime', models.TimeField(blank=True)),
                ('origin', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
                ('capacity', models.IntegerField(default=100)),
                ('available', models.BooleanField(default=True)),
                ('rules', models.TextField(default='\n        از زمان صدور تا ساعت ۱۲ ظهر روز قبل از حرکت\n        %10 جریمه\n        از ۱۲ ظهر روز قبل تا ۳ ساعت قبل از حرکت قطار\n        %30 جریمه\n        از ۳ ساعت قبل از حرکت قطار تا لحظه حرکت\n        %50 جریمه\n        پس از حرکت قطار\n        %100 جریمه')),
                ('services', models.TextField(default='catering, train resturant available')),
            ],
            options={
                'db_table': 'existtrains',
            },
        ),
    ]
