# Generated by Django 5.2.6 on 2025-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existtrains',
            name='price',
            field=models.BigIntegerField(default=2000000),
        ),
    ]
